### ISSUE TITLE
Add a customization to enable the rainbow color header

### ISSUE THREAD

**Issue by sakuramochi0** [sakuramochi0/prichan-stylesheet#6]
I noticed that Stylus has a feature to customize a stylesheet depending on a user preference: [Writing UserCSS · openstyles/stylus Wiki · GitHub](https://github.com/openstyles/stylus/wiki/Writing-UserCSS). With this feature, I'd like to add an option to change the header color to the rainbow one. 🌈

**Example screenshot**

<img width="732" alt="Screen Shot 2021-08-24 at 21 04 38" src="https://user-images.githubusercontent.com/6568716/130614208-af4bdb20-95e6-4087-a11d-3689290e21c4.png">

We would be able to use this color gradient CSS:

```css
    :root {
        --rainbow-header: linear-gradient(45deg,
        #da98f6, #c39af5, #ac9cf5, #a7a9f6,
        #aff3f6, #affff1, #aeffd9, #afffc3,
        #afffb0, #bdffab, #d4ffae, #edffaf,
        #fbfdae, #f8dfad, #f4b9aa, #f3a1a7, #f29ca9);
    }
```
